services:
  - type: web
    name: wepsun-backend-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate
    startCommand: npx tsx backend/src/server.ts
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
